export const environment = {
  dev: false,
  qa: false,
  uat: false,
  production: true,
  local: false,
  encryptionKey: 'unifiedReports',
  // blobKey : "?sv=2020-02-10&ss=b&srt=sco&sp=rwdlactfx&se=2121-07-05T12:33:56Z&st=2021-07-05T04:33:56Z&spr=https&sig=LAL2dTXStLF0Qgyd6%2FiPjw5xjMR0kmR2kB7bZmudHdY%3D",
  blobKey : "",

  API_BASE_URL: 'https://skilledge.lntedutech.com',
  NODE_EDGE_URL: 'https://skilledge.lntedutech.com',
  NODE_URL:  'https://uapcoreservice.lntedutech.com',
  PROCTOR_URL : 'http://lntproctor.lntedutech.com/api/storage/',
  PROCTOR : 'https://lntproctor.lntedutech.com',
  MONGOCHARTURL: 'https://charts.mongodb.com/charts-microcertuat-gzomw',
  OFFCAMPUSDRIVE:'https://campus.lntedutech.com/l#/open/off-campus/profile',
  CAMPUS_URL:'https://campus.lntedutech.com/l#/login',
  SKILL_EDGE_URL :'https://skilledge.lntedutech.com',
  SKILL_PROFILE_URL :'https://profile.lntedutech.com',
  cryptoEncryptionKey:"(!@#Passcode!@#)",
  SKILL_EDGE_URL: "https://skillexchange.lntedutech.com",
  blobToken:"?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2221-11-23T19:12:41Z&st=2021-11-23T11:12:41Z&spr=https,http&sig=R6%2BlZGrzjuFs1aAy2uUG%2BNkjVig5%2F8disv01i86VK8M%3D",
};
