apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifiedreportuat
  namespace: unifiedrpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifiedreportuat
  template:
    metadata:
      labels:
        app: unifiedreportuat
    spec:
      containers:
        - name: unifiedreportuat
          image: assessmentecouat.azurecr.io/unifiedreportuat:$tag
          resources:
           limits:
             cpu: "1"
             memory: "4Gi"
           requests:
             cpu: "500m"
             memory: "2Gi"
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: mysecret2
      nodeSelector:
        agentpool: uapuat