apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifiedreportuat
  namespace: skillexchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifiedreportuat
  template:
    metadata:
      labels:
        app: unifiedreportuat
    spec:
      containers:
        - name: unifiedreportuat
          image: uapuat.azurecr.io/unifiedreportuat:$tag
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: mysecret2
      nodeSelector:
        agentpool: uapuat