apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifiedreportqa
  namespace: skillexchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifiedreportqa
  template:
    metadata:
      labels:
        app: unifiedreportqa
    spec:
      containers:
        - name: unifiedreportqa
          image: skillexchangedev.azurecr.io/unifiedreportqa:$tag
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: mysecret