apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifiedreport
  namespace: unifiedrpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifiedreport
  template:
    metadata:
      labels:
        app: unifiedreport
    spec:
      containers:
        - name: unifiedreport
          image: skillexchangedev.azurecr.io/unifiedreport:$tag
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: mysecret